[build]
  # Build command
  command = "npm run build:netlify"
  
  # Build directory
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  GENERATE_SOURCEMAP = "false"
  NODE_ENV = "production"
  REACT_APP_JWT_SECRET = "your_secure_jwt_secret_here_change_in_production"
  REACT_APP_ADMIN_USERNAME = "admin"
  REACT_APP_ADMIN_PASSWORD = "admin123"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https: https://images.unsplash.com https://cdn.balikturleri.com https://cdn.myikas.com https://www.ideasoft.com.tr; connect-src 'self' https:; worker-src 'self' blob:; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"

# Fix JavaScript chunks - more specific patterns
[[headers]]
  for = "/static/js/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

# Fix CSS files - more specific patterns
[[headers]]
  for = "/static/css/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"
    Cache-Control = "public, max-age=31536000, immutable"

# Manifest and other assets
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

# Logo files
[[headers]]
  for = "/logo192.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/logo512.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=86400"

# Image files
[[headers]]
  for = "*.png"
  [headers.values]
    Content-Type = "image/png"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.ico"
  [headers.values]
    Content-Type = "image/x-icon"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Content-Type = "image/jpeg"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "*.webp"
  [headers.values]
    Content-Type = "image/webp"
    Cache-Control = "public, max-age=86400"

# Other static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/javascript"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https:; img-src 'self' data: https: https://images.unsplash.com https://cdn.balikturleri.com https://cdn.myikas.com https://www.ideasoft.com.tr;"

# Static assets - these must be served directly without redirects
# Netlify should serve these files directly from the build directory

# Redirects are handled by _redirects file
# This ensures proper static asset serving
