services:
  - type: static
    name: sedefak-website
    env: static
    buildCommand: npm ci && npm run build
    publish: build
    headers:
      - path: "/*"
        name: "Cache-Control"
        value: "public, max-age=600"
    redirects:
      # Serve static assets directly
      - source: "/static/*"
        destination: "/static/:splat"
        status: 200
      - source: "/*.css"
        destination: "/:splat"
        status: 200
      - source: "/*.js"
        destination: "/:splat"
        status: 200
      - source: "/*.chunk.js"
        destination: "/:splat"
        status: 200
      # SPA routes -> index.html
      - source: "/category/*"
        destination: "/index.html"
        status: 200
      - source: "/product/*"
        destination: "/index.html"
        status: 200
      - source: "/contact"
        destination: "/index.html"
        status: 200
      - source: "/admin"
        destination: "/index.html"
        status: 200
      - source: "/search"
        destination: "/index.html"
        status: 200
      - source: "/guide"
        destination: "/index.html"
        status: 200
      # Catch-all
      - source: "/*"
        destination: "/index.html"
        status: 200

